# Helm chart values
# values.yaml for OpenTelemetry Collector
mode: daemonset 

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  pullPolicy: IfNotPresent

extraEnvs:
  - name: GRAFANA_CLOUD_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-cloud-config
        key: password
# Example configuration: OTLP receiver to get data from applications, and a logging exporter for verification
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80 
      spike_limit_percentage: 15

  exporters:
    debug:
      verbosity: detailed
    # Add your actual backend exporter here (e.g., prometheus, otlphttp to SigNoz, Jaeger, etc.)
    prometheus:
      endpoint: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090"
      tls:
        insecure: true
    loki:
      endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      labels:
        job: "otel-collector"
      format: json
    tempo:
      endpoint: "http://tempo-distributed.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    # otlp/grafana-cloud:
    #   endpoint: "https://otlp-gateway-prod-eu-west-0.grafana.net:443"
    #   headers:
    #     "Authorization": "Bearer <GRAFANA_CLOUD_API_KEY>"
  
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        receivers: 
          - otlp
          - hostmetrics
        processors: 
          - batch
          - memory_limiter
        exporters: 
          - debug
          #- otlp/grafana-cloud
          - prometheus
      traces:
        receivers: 
          - otlp
        processors: 
          - batch
          - memory_limiter
        exporters: 
          - debug
          #- otlp/grafana-cloud
          - tempo
      logs:
        receivers: 
          - otlp
        processors: 
          - batch
          - memory_limiter
        exporters: 
          - debug
          - loki